import 'package:al_mushrif/src/core/utils/app_colors.dart';
import 'package:al_mushrif/src/core/utils/app_sizes.dart';
import 'package:al_mushrif/src/core/widgets/custom_appBar.dart';
import 'package:al_mushrif/src/core/widgets/custom_text.dart';
import 'package:al_mushrif/src/core/widgets/custom_text_field.dart';
import 'package:al_mushrif/src/core/widgets/custom_vip_card.dart';
import 'package:al_mushrif/src/features/categories/categories_imports.dart';
import 'package:al_mushrif/src/features/orders/orders_imports.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

part  'presentation/screens/home_screen.dart';
part 'presentation/widgets/home_widgets/search_bar.dart';
part 'presentation/widgets/home_widgets/image_card.dart';
part '../../core/widgets/category_item_circle.dart';
part 'presentation/widgets/home_widgets/categories_gridview.dart';
part 'presentation/widgets/home_widgets/bannar.dart';
part 'presentation/widgets/notification/notification_page.dart';
part 'presentation/widgets/notification/notification_card.dart';