import 'package:al_mushrif/src/core/utils/app_colors.dart';
import 'package:al_mushrif/src/core/utils/app_sizes.dart';
import 'package:al_mushrif/src/core/widgets/QtyButton.dart';
import 'package:al_mushrif/src/core/widgets/custom_appBar.dart';
import 'package:al_mushrif/src/core/widgets/custom_button.dart';
import 'package:al_mushrif/src/core/widgets/custom_outLine_button.dart';
import 'package:al_mushrif/src/core/widgets/custom_text.dart';
import 'package:al_mushrif/src/core/widgets/custom_text_field.dart';
import 'package:al_mushrif/src/features/address/address_imports.dart';
import 'package:al_mushrif/src/features/app_layout/app_layout_imports.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'presentation/widgets/payment_widgets/payment_sheet.dart';

part 'presentation/screens/cart_screen.dart';
part 'presentation/widgets/cart_widgets/checkout_steps.dart';
part 'presentation/widgets/cart_widgets/cart_item_card.dart';
part 'presentation/widgets/shipping_widgets/shipping_page.dart';
part 'presentation/widgets/shipping_widgets/address_item_card.dart';
part 'presentation/widgets/delivery_widgets/delivery_page.dart';
part 'presentation/widgets/delivery_widgets/delivery_cart_item.dart';
part 'presentation/widgets/delivery_widgets/radio_delivery_type.dart';
part 'presentation/widgets/delivery_widgets/pickup_bottom_sheet.dart';
part 'presentation/widgets/delivery_widgets/choose_delivery_type.dart';
part 'presentation/widgets/payment_widgets/payment_page.dart';
part 'presentation/widgets/payment_widgets/pay_switch.dart';
part 'presentation/widgets/payment_widgets/delivery_instructions_item.dart';
part 'presentation/widgets/payment_widgets/payment_method.dart';
part 'presentation/widgets/payment_widgets/payment_card.dart';
part 'presentation/widgets/payment_widgets/gift_bottom_sheet.dart';
part 'presentation/widgets/payment_widgets/text_field_bottom_sheet.dart';
part 'presentation/widgets/payment_widgets/invoice_row.dart';
part 'presentation/widgets/payment_widgets/invoice_summary_card.dart';
part 'presentation/widgets/payment_widgets/fees_bottom_sheet.dart';
part 'presentation/widgets/payment_widgets/shareholder_bottom_sheet.dart';
part 'presentation/widgets/payment_widgets/delivery_bottom_sheet.dart';
part 'presentation/widgets/payment_widgets/allow_replacement.dart';
part 'presentation/widgets/payment_widgets/confirmation_bottom_sheet.dart';

part 'presentation/widgets/success_widgets/success_page.dart';
part 'presentation/widgets/success_widgets/order_item.dart';
part 'presentation/widgets/success_widgets/product_section.dart';
part 'presentation/widgets/success_widgets/order_info.dart';
part 'presentation/widgets/success_widgets/row_order_info.dart';
part 'presentation/widgets/success_widgets/product_item.dart';
part 'presentation/widgets/success_widgets/track_order_page.dart';
part 'presentation/widgets/success_widgets/OrderStatusTile.dart';

